# Generated by Django 5.2.7 on 2025-11-20 04:34

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('business_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('contact_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Upi', 'Upi'), ('Card', 'Card')], max_length=255, null=True)),
                ('subscription_start', models.DateField(auto_now_add=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('subscription_amount', models.DecimalField(decimal_places=2, default=5000.0, help_text='Subscription amount in INR', max_digits=8)),
                ('subscription_currency', models.CharField(default='INR', help_text='Currency code for the subscription (e.g., INR, USD, AED)', max_length=10)),
                ('currency_emoji', models.CharField(blank=True, help_text='Emoji representation of the currency (e.g., ₹, 💵, 💶)', max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='adminapp.category')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days', models.CharField(blank=True, help_text='e.g. Mon-Fri', max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_name', models.CharField(help_text='Guardian or parent name.', max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, help_text='The actual enrollment date of the member, used for billing calculations.', null=True)),
                ('subscription_term', models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('A', 'Annual')], max_length=1)),
                ('outstanding_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Initial debt carried forward from before the app usage.', max_digits=10)),
                ('recurring_date', models.PositiveSmallIntegerField(blank=True, help_text='Day of the month (1–31) when recurring fee is due.', null=True)),
                ('batch_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='adminapp.batch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('tuition_fees', models.PositiveIntegerField()),
                ('tuition_recurring', models.BooleanField(default=False)),
                ('admission_fees', models.PositiveIntegerField()),
                ('management_fees', models.PositiveIntegerField()),
                ('management_recurring', models.BooleanField(default=False)),
                ('uniform_fees', models.PositiveIntegerField()),
                ('uniform_recurring', models.BooleanField(default=False)),
                ('transport_fees', models.PositiveIntegerField()),
                ('transport_recurring', models.BooleanField(default=False)),
                ('book_fees', models.PositiveIntegerField()),
                ('book_recurring', models.BooleanField(default=False)),
                ('other_fees', models.PositiveIntegerField()),
                ('other_recurring', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('gpay', 'GPay')], max_length=10)),
                ('tuition_paid', models.BooleanField(default=False)),
                ('admission_paid', models.BooleanField(default=False)),
                ('management_paid', models.BooleanField(default=False)),
                ('uniform_paid', models.BooleanField(default=False)),
                ('transport_paid', models.BooleanField(default=False)),
                ('book_paid', models.BooleanField(default=False)),
                ('other_paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.member')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_members', to='adminapp.subscription'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('present', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='adminapp.member')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('customer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(help_text='Month number (1=Jan, 12=Dec)')),
                ('year', models.PositiveIntegerField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Due', 'Due')], default='Due', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='adminapp.member')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('customer', 'month', 'year')},
            },
        ),
    ]
