# Generated by Django 5.2.7 on 2025-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='initial_outstanding',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='recurring_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
